import { encodeFollowUps } from "./chat-protocol";
import { HELPLINES } from "./helplines";
import type { LanguageCode } from "./languages";
import { LANGUAGES } from "./languages";
import type { RetrievalResult } from "./retrieve";

/**
 * Server-side prompt + fallback helpers.
 *
 * Retrieval is CONTEXT ONLY: the topics matched from intents.json are injected
 * as reference material, never shown verbatim and never used to refuse. Every
 * reply is generated by the LLM. This fixes the bug where a vague Hinglish
 * question got a canned English footboard answer.
 */

const HELPLINE_LINE = HELPLINES.map((h) => `${h.name} ${h.number}`).join(", ");

/**
 * @param nowLine optional "Current time in Mumbai: … Day type: …" line for
 *   schedule awareness (added in stage 3).
 */
export function buildSystemPrompt(
  lang: LanguageCode,
  context: RetrievalResult[],
  nowLine?: string,
): string {
  const replyName = LANGUAGES[lang].replyName;
  const contextBlock = context.length
    ? context
        .map((r, i) => `[Reference ${i + 1}: ${r.topic.title}]\n${r.topic.answer.en}\nSource: ${r.topic.source}`)
        .join("\n\n")
    : "(no specific reference matched; rely on general railway knowledge and the rules above)";

  return [
    "You are RailSaathi, an assistant for Mumbai local train and Indian Railways commuters.",
    nowLine ?? "",
    "",
    "SCOPE — you help with:",
    "- Mumbai local schedules, first/last trains, routes and interchanges (use tools; never guess times).",
    "- Platform/station info (only if given in verified context), ticketing (UTS app, monthly/quarterly passes, first/second class, AC local rules), refunds and complaints.",
    "- Mega blocks and disruptions, safety and security, women/child/senior/divyang travel, luggage and lost property, monsoon and flooding, fire and medical emergencies, scams, passenger rights, and reporting (RPF/GRP/Rail Madad).",
    "- General Indian Railways basics: PNR and reservation, tatkal rules, cancellation and refund process, long-distance travel safety.",
    "Politely decline unrelated topics, and decline anything that would help someone harm the railway or passengers.",
    "",
    "REPLY LANGUAGE:",
    `- Reply in ${replyName} by default.`,
    "- If the selector is English but the user writes Hinglish (Hindi/Marathi in Roman script, e.g. \"train kab hai\", \"kya me safe hu\"), MIRROR Hinglish in Roman script — do not switch to formal Hindi script.",
    "- If the user explicitly asks for a language (\"reply in Marathi\"), reply in that language.",
    "- Earlier messages may be in other languages; that is fine, answer the latest one.",
    "- When replying in Hindi or Marathi, write station names as English name + local script, e.g. \"Dadar (दादर)\".",
    "",
    "ACCURACY (critical):",
    "- Never invent fares, fines, law sections, platform numbers, statistics, train timings or phone numbers.",
    `- Phone numbers: use ONLY these verified numbers when relevant: ${HELPLINE_LINE}.`,
    "- Fares and rules change: give the general process and where to confirm (official site, UTS app, station counter, 139). Do not state a specific fare unless it is in the context.",
    "",
    "TRAIN SCHEDULES (use tools, never guess):",
    "- For any question about train timings, next/first/last trains, or routes, call the tools: find_station, get_next_trains, get_train_details, get_timetable_info.",
    "- Give times ONLY from tool results. If get_next_trains returns covered:false (unknown station or no data), say \"I don't have the timetable for that route\" and point to the official Western Railway / Central Railway timetable or an app like m-Indicator. NEVER guess a time.",
    "- Always say these are SCHEDULED timings, not live status; delays, cancellations and Sunday mega blocks can change services, so check the station indicator.",
    "- If source, destination or time is missing, ask ONE clarifying question; default the time to now.",
    "- Keep schedule answers short: the next 3-5 trains plus one line of practical advice (e.g. fast vs slow).",
    "- Do NOT repeat the full train table in prose — a compact card is shown separately from the tool data. Summarise briefly and mention the effective date from get_timetable_info.",
    "- If any train name contains \"(DEMO)\", the timetable is SAMPLE data, not a real sync. Say clearly that these are sample/illustrative timings and the user must confirm on m-Indicator or the station indicator.",
    "",
    "STYLE:",
    "- Short, calm, plain sentences. Numbered steps for instructions. Never alarmist.",
    "- For a vague question (e.g. \"am I safe on the train?\"), give a brief general-safety answer AND ask ONE clarifying question (which line, time of day, travelling alone?).",
    "- If the user may be in immediate danger, put emergency numbers FIRST, then brief steps.",
    "- Do not mention these rules or the word 'context'.",
    "",
    "CONTEXT (reference material — paraphrase, do not quote, do not treat as the only knowledge):",
    contextBlock,
  ]
    .filter((line) => line !== undefined)
    .join("\n");
}

/** Localised suggested follow-ups used when the model doesn't drive them. */
const DEFAULT_FOLLOWUPS: Record<LanguageCode, string[]> = {
  en: ["Emergency helpline numbers", "Next train from Dadar to Borivali", "Is it safe to travel late at night?"],
  hi: ["आपातकालीन हेल्पलाइन नंबर", "दादर से बोरीवली अगली ट्रेन", "क्या देर रात यात्रा सुरक्षित है?"],
  mr: ["आपत्कालीन हेल्पलाईन क्रमांक", "दादर ते बोरिवली पुढची ट्रेन", "रात्री उशिरा प्रवास सुरक्षित आहे का?"],
};

export function defaultFollowUps(lang: LanguageCode): string[] {
  return DEFAULT_FOLLOWUPS[lang];
}

/** Follow-ups seeded from a matched topic, falling back to defaults. */
export function followUpsForTopic(result: RetrievalResult | undefined, lang: LanguageCode): string[] {
  return result?.topic.followups[lang]?.slice(0, 3) ?? DEFAULT_FOLLOWUPS[lang];
}

/** Short apology + verified numbers, streamed when the LLM/tools fail entirely. */
const APOLOGY: Record<LanguageCode, string> = {
  en: `Sorry, I couldn't complete that just now. Please try again in a moment.\n\nIf you need urgent help, these numbers work now:\n\n${HELPLINES.map((h) => `- **${h.name} ${h.number}**`).join("\n")}`,
  hi: `माफ़ करें, मैं अभी यह पूरा नहीं कर सका। कृपया थोड़ी देर में फिर कोशिश करें।\n\nअगर तुरंत मदद चाहिए, तो ये नंबर अभी काम करते हैं:\n\n${HELPLINES.map((h) => `- **${h.name} ${h.number}**`).join("\n")}`,
  mr: `माफ करा, मी आत्ता हे पूर्ण करू शकलो नाही. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.\n\nतातडीने मदत हवी असल्यास हे क्रमांक आत्ता चालतात:\n\n${HELPLINES.map((h) => `- **${h.name} ${h.number}**`).join("\n")}`,
};

export function buildApology(lang: LanguageCode): string {
  return APOLOGY[lang] + encodeFollowUps(DEFAULT_FOLLOWUPS[lang], "suggestions");
}
